### ISSUE TITLE
Respect timezone on post save.

### ISSUE THREAD

**Issue by rygos** [m1k1o/blog#14]
Since the time zone cannot be specified anywhere, the wrong time zone is always saved when writing a post. In my case two hours early.

**Comment by m1k1o** [comment]
Hey, @rygos thank you for your issue. This should fix your problem.

**Comment by rygos** [comment]
@m1k1o , thank you very much. For your solution is docker needed, right? I'm using a installation without docker =)

**Comment by m1k1o** [comment]
@rygos you are right, it should not be needed.

I changed solution, so it can be set up in config but I also left compatibiltiy with `TZ` environment variable.
