### ISSUE TITLE
Document friends feature

### ISSUE THREAD

**Issue by FixFlare** [m1k1o/blog#17]
I don't understand after reading the readme how it determines who is friend vs who is public.

Please document what you mean by this and how we control who friends are.

**Comment by m1k1o** [comment]
In your `config.ini` you can specify their `username` and `password`. In docker environment variables, I think it's not possible (yet).

https://github.com/m1k1o/blog/blob/927d7690454ea5f742916414d6c0f72493df7d4b/config.ini#L42-L44

e.g. `jane` with `mysecretpass` and `thomas` with `anotherpass`:
```ini
[visitors] 
visitor[jane] = mysecretpass
visitor[thomas] = anotherpass
```

You are right, they are called visitors not friends, it should be properly named and documented. I'm planning in the future to add encrypted passwords feature.

**Comment by FixFlare** [comment]
Thanks for the quick response. Yeah, I'm using docker so it would be nice if variables were supported for that.

Would be good to copy/paste this info into the readme IMO.

Thanks again,

**Comment by m1k1o** [comment]
@BenevolentD updated readme with instructions and added docker support for friends.

Thanks for pointing that out!
