### ISSUE TITLE
Photos from phone posting sideways

### ISSUE THREAD

**Issue by ItsNoted** [m1k1o/blog#20]
Mobile photos are posting sideways. Seems to be a common thing for blogs and posting from your phone. If you can fix that you have a winner!

**Comment by m1k1o** [comment]
I'll look into that. Maybe picture rotation is only stored in exif data, which is my blog ignoring.

**Comment by m1k1o** [comment]
@geekedtv could you please provide sample picture? Maybe zipped, so that githut won't modificate it in any way.

**Comment by geekedtv** [comment]
Hi, sorry for the late reply. I am circling back looking at this to use for personal blog. Any photo I add from my iPhone that I take myself seems to post sideways on the blog. Also, any chance of letting videos upload? I would really like that for memories!

**Comment by m1k1o** [comment]
Found the issue. Exif library is missing in dockerimage. I'm posing fix today..
