### ISSUE TITLE
403 - Forbidden: Access is Denied

### ISSUE THREAD

**Issue by StarRico** [m1k1o/blog#23]
I can see the page but on other devices I get "403 - Forbidden: Access is Denied. You do not have permission to view this directory or page." Guessing there's a setting somewhere to allow access to it?

**Comment by m1k1o** [comment]
That is weird. If that would happen on all the devices, then it is definitely problem with [direcotry pesmissions](https://github.com/m1k1o/blog#correct-permissions).

Could you please share more information about your setup, so that I can try to replicate your problem?

**Comment by StarRico** [comment]
Ahh I actually think it's an issue with the domain itself. So closing this as an issue. Great work by the way!!!!
