### ISSUE TITLE
Unable to enable Dark Mode.

### ISSUE THREAD

**Issue by juneflowers** [m1k1o/blog#26]
Hey I'm losing my mind trying to figure out how to set dark mode. I've tried "theme02-dark" since thats the filename of the dark screenshot but have had no luck.

**Comment by m1k1o** [comment]
Hey, dark mode settings are inherited from your system (browser) settings. https://support.google.com/chrome/answer/9275525?co=GENIE.Platform=Android&hl=en

Currently, there is no way how to force dark mode even for light mode devices.

**Comment by juneflowers** [comment]
Aww that's really disappointing
