### ISSUE TITLE
Tags doens't work with postgres

### ISSUE THREAD

**Issue by ozzyst** [m1k1o/blog#32]
Hello again!

I've deployed your blog in Kube with my own Postgres it works fine! Thanks! But it has a problem with tags

`SQLSTATE[42P18]: Indeterminate datatype: 7 ERROR: could not determine data type of parameter $1`

The same bad issue with location :(

**Comment by m1k1o** [comment]
Thanks, i'll look into it. It seems like just syntax is different from Sqlite & Mysql.

**Comment by m1k1o** [comment]
@ozzyst it should be fixed, can you test it please?

**Comment by ozzyst** [comment]
@m1k1o yep. I can test it today.

**Comment by ozzyst** [comment]
Tags and geo work! Thanks!
