### ISSUE TITLE
Lost "Login"

### ISSUE THREAD

**Issue by ozzyst** [m1k1o/blog#35]
Hey there! I hope you're well!

I've updated the latest image and I have had a problem. The button login has been lost, also I can't see my posts. Screenshot here - https://ibb.co/y03GRL3

The browser console is empty, has no errors. I see no errors in my logs too.

Any ideas?

**Comment by m1k1o** [comment]
Hi, it looks like last PR https://github.com/m1k1o/blog/pull/34 broke it. Thanks for reporting.
