### ISSUE TITLE
SQLSTATE[08006] [7] invalid connection option "unix_socket"

### ISSUE THREAD

**Issue by Brancliff** [m1k1o/blog#38]
New user trying to set things up here. Just set up the docker-compose using postgres. When opening the webpage, I get the error "SQLSTATE[08006] [7] invalid connection option "unix_socket"" as a red popup in the bottom left. I can log in, but I can't post.

If you need more information, let me know! I could give you my folder structure, docker-compose, or the logs from either container if necessary. I just want to make sure if this is something wrong on my end or not, I'm getting more used to docker but I'm not great with linux :s

**Comment by m1k1o** [comment]
Hi. So i am assuming you use `unix_socket` as connection. Could you try to set up connection using host? Or setting that unix socket to host (accodding to [this answer](https://stackoverflow.com/a/17138309/1113204)).
