### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by merlin699** [m1k1o/blog#42]
Hi,
I'm running **_blog_** in docker with sqlite.
Is there a way to change the favicon? Didn't find anything in the config.ini.
Thanks a lot!

**Comment by m1k1o** [comment]
Hi. There is no config value for that, but you can mount it to the path of the existing favicon, thus replacing it.

```
-v "/path/to/your/favicon.ico:/var/www/html/favicon.ico"
```

When using docker-compose add to volumes:

```yaml
volumes:
  - "/path/to/your/favicon.ico:/var/www/html/favicon.ico"
```

**Comment by merlin699** [comment]
Thanks a lot, works perfectly!
