### ISSUE TITLE
Truenas scale can't post on blog SQLSTABLE[42P01] errors

### ISSUE THREAD

**Issue by hardelone** [m1k1o/blog#45]
Hello.
I have Truenas Scale and when I install this app, I can't do anything

when I open app, error >  
SQLSTABLE[42P01]: Undefined tanle: 7 error: relation "post" does not exist LINE 5: FROM "posts"

when I tried to post  > SQLSTABLE[42P01]: Undefined tanle: 7 error: relation "post" does not exist LINE 1: INSERT INTO "posts" ("text", "plain_text", "feeling", "perso...

can you help me? I tried dataset with permisions on www-data, root, apps, even me and nothing working.

**Comment by m1k1o** [comment]
Looks like you don't have created tables. Do you use MySQL, Postgres or Sqlite?

**Comment by hardelone** [comment]
> Looks like you don't have created tables. Do you use MySQL, Postgres or Sqlite?

to be honest, I don't know. When installing in truena scale there was no choice, I left everything default.

**Comment by m1k1o** [comment]
Might be this one it?
https://artifacthub.io/packages/helm/nicholaswilde/blog

I did not create that, here seems to be the repo and maintainer for that:
https://github.com/nicholaswilde/helm-charts/tree/main/charts/blog
https://github.com/nicholaswilde/docker-blog

**Comment by m1k1o** [comment]
But I see it uses mysql, if you could remove volume for mysql and start it again, it should correctly create tables.
