### ISSUE TITLE
Default privacy mode

### ISSUE THREAD

**Issue by derixithy** [m1k1o/blog#47]
How to set the default privacy mode to for example public.
I will only post public posts and it would be handy if the privacy settings persist or is change able

**Comment by m1k1o** [comment]
You could theoretically change this value to public and you will have default privacy to public:
https://github.com/m1k1o/blog/blob/afa89836d259da0b7e1351e4b84ded271c3ff2ee/static/scripts/app.js#L327

Or you can remove this line, effectively disabling privacy function and everything will be public no matter what the setting says. 
https://github.com/m1k1o/blog/blob/afa89836d259da0b7e1351e4b84ded271c3ff2ee/app/post.class.php#L444C35-L444C35

Then you could just hide this element with `style="visibility:hidden;"`.
https://github.com/m1k1o/blog/blob/afa89836d259da0b7e1351e4b84ded271c3ff2ee/index.php#L311-L315

**Comment by derixithy** [comment]
Thank you that worked!
