### ISSUE TITLE
Picture issues

### ISSUE THREAD

**Issue by Skinsly** [m1k1o/blog#52]
Excuse me. How can the three pictures mentioned above (pic_small = static/images/profile.jpg, pic_big = static/images/profile_big.jpg, cover = static/images/cover.jpg) be set so that they can be displayed?

**Comment by m1k1o** [comment]
By copying config.ini to data folder, that is mounted to the docker image and changing it there in ini file.
https://github.com/m1k1o/blog?tab=readme-ov-file#step-2-create-data-directory-and-download-configini-file

**Comment by Skinsly** [comment]
> config.ini

The config.ini file is already in place. However, I just don't know what operations can be carried out to replace these three default pictures.

**Comment by Skinsly** [comment]
![1733fc13-c93f-48ba-8e7f-b2ba9e707a54](https://github.com/user-attachments/assets/c6d7cc01-18c0-4cf8-92b7-ece083f75063)
There are only these two files in the Dota folder, right? Do the replacement pictures need to be put in here? And how to put them?

**Comment by m1k1o** [comment]
Yes. Put your images there and update `config.ini` accordingly e.g. `data/image.jpeg` can be the new value.

**Comment by Skinsly** [comment]
> Yes. Put your images there and update `config.ini` accordingly e.g. `data/image.jpeg` can be the new value.

It's done. Thank you.
