### ISSUE TITLE
YouTube address

### ISSUE THREAD

**Issue by Skinsly** [m1k1o/blog#53]
![a8cc27d6-7f3a-4bd8-b7bb-d4b039824d34](https://github.com/user-attachments/assets/219a912c-9dd9-484a-8b03-8f52fcbbc123)
Doesn't the YouTube address generate a preview image automatically?

**Comment by m1k1o** [comment]
It does for me when i use my home connection:
![image](https://github.com/user-attachments/assets/9e4c752b-3523-465e-8bb0-8cc0a0b3a425)

But not when I use cloud service:
![image](https://github.com/user-attachments/assets/e2b7901b-489b-46d1-bb60-0cd3bb2a86d5)

Probably you host your blog on some Datacenter IP where youtube is blocked, what is my second case. You can set up [proxy](https://github.com/m1k1o/blog/blob/7be5f90d8fef4da97310a328ee7ff2ab177542e0/config.ini#L61-L66) using non-blocked IPs.
